const colors = {
  light: {
    text: '#2D1B0E',
    tint: '#C4714A',
    background: '#FDF8F3',
    foreground: '#2D1B0E',
    card: '#FFF5EC',
    cardForeground: '#2D1B0E',
    primary: '#C4714A',
    primaryForeground: '#FFFFFF',
    secondary: '#F5E9DC',
    secondaryForeground: '#4A2F1A',
    muted: '#EDD9C8',
    mutedForeground: '#9B7560',
    accent: '#E07B5A',
    accentForeground: '#FFFFFF',
    destructive: '#C0392B',
    destructiveForeground: '#FFFFFF',
    border: '#E2CEBC',
    input: '#E5D5C5',
  },
  dark: {
    text: '#F5E6D3',
    tint: '#D4845C',
    background: '#1A0F08',
    foreground: '#F5E6D3',
    card: '#2A1A10',
    cardForeground: '#F5E6D3',
    primary: '#D4845C',
    primaryForeground: '#FFFFFF',
    secondary: '#3D2515',
    secondaryForeground: '#F5E6D3',
    muted: '#3D2515',
    mutedForeground: '#A08065',
    accent: '#D4845C',
    accentForeground: '#FFFFFF',
    destructive: '#E74C3C',
    destructiveForeground: '#FFFFFF',
    border: '#4A2F1A',
    input: '#4A2F1A',
  },
  radius: 16,
};

export default colors;
